version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:cached
    environment:
        POSTGRES_PASSWORD: password
  app:
    build: 
        context: ./app/
        args:
            - RUBY_VERSION=3.0
            - PG_MAJOR=13
            - NODE_MAJOR=16
            - YARN_VERSION=1.22.5
            - BUNDLER_VERSION=2.1.4
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./app:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db